from docx import Document
from docx.shared import Pt, RGBColor, Inches
from docx.enum.text import WD_ALIGN_PARAGRAPH
from datetime import datetime
import io

def create_cam(analysis_result: dict, application) -> io.BytesIO:
    doc = Document()
    
    # Cover Page
    doc.add_heading("CONFIDENTIAL — CREDIT APPRAISAL MEMORANDUM", 0)
    
    p = doc.add_paragraph()
    p.add_run(f"Company Name: {application.company_name}\\n").bold = True
    p.add_run(f"CIN: {application.cin}\\n").bold = True
    p.add_run(f"Date Generated: {datetime.now().strftime('%Y-%m-%d %H:%M:%S')}\\n").bold = True
    
    p = doc.add_paragraph("Generated by IntelliCredit AI Engine", style='Intense Quote')
    
    # Section 1 - Exec Summary
    doc.add_heading("Section 1 — Executive Summary", 1)
    doc.add_paragraph(analysis_result.get("analysis_summary", ""))
    
    scor = analysis_result.get("scoring", {})
    rec = analysis_result.get("lending_recommendation", {})
    grade = scor.get("grade", "N/A")
    rec_action = scor.get("recommended_action", "N/A")
    
    p_box = doc.add_paragraph()
    r = p_box.add_run(f"Recommendation: {rec_action} (Grade: {grade}) | Total Score: {scor.get('total_score')} \\n")
    r.bold = True
    p_box.add_run(f"Suggested Limit: ₹{rec.get('suggested_limit_crores')} Cr at {rec.get('interest_rate_pct')}%")
    
    # Section 2
    doc.add_heading("Section 2 — Five Cs Analysis", 1)
    five = analysis_result.get("five_cs", {})
    for k, v in five.items():
        doc.add_heading(k.capitalize(), 2)
        doc.add_paragraph(v)
        
    # Section 3
    doc.add_heading("Section 3 — Financial Snapshot", 1)
    fin = analysis_result.get("extracted_financials", {})
    table = doc.add_table(rows=1, cols=2)
    table.style = 'Table Grid'
    hdr = table.rows[0].cells
    hdr[0].text = 'Metric'
    hdr[1].text = 'Value'
    for k, v in fin.items():
        row = table.add_row().cells
        row[0].text = str(k).replace('_', ' ').capitalize()
        row[1].text = str(v)
        
    # Section 4
    doc.add_heading("Section 4 — Dimension Score Dashboard", 1)
    dims = analysis_result.get("dimension_scores", {})
    table2 = doc.add_table(rows=1, cols=3)
    table2.style = 'Table Grid'
    h2 = table2.rows[0].cells
    h2[0].text = 'Dimension'
    h2[1].text = 'Score'
    h2[2].text = 'Rationale'
    for k, v in dims.items():
        row = table2.add_row().cells
        row[0].text = str(k).replace('_', ' ').capitalize()
        row[1].text = str(v.get("score"))
        row[2].text = str(v.get("rationale"))
        
    # Section 5
    doc.add_heading("Section 5 — Counterfactual Recommendations", 1)
    cfs = analysis_result.get("counterfactuals", [])
    for c in cfs:
        doc.add_paragraph(f"{c.get('dimension')} - {c.get('action')} (Ease: {c.get('ease')})", style='List Number')
        
    # Section 6
    doc.add_heading("Section 6 — Strengths & Risks", 1)
    doc.add_heading("Strengths", 2)
    for s in analysis_result.get("strengths", []):
        doc.add_paragraph(str(s), style='List Bullet')
    doc.add_heading("Risks", 2)
    for r in analysis_result.get("risks", []):
        doc.add_paragraph(str(r), style='List Bullet')
        
    # Section 7
    doc.add_heading("Section 7 — Director Summary", 1)
    dirs = analysis_result.get("directors", [])
    t3 = doc.add_table(rows=1, cols=2)
    t3.style = 'Table Grid'
    h3 = t3.rows[0].cells
    h3[0].text = 'Name'
    h3[1].text = 'Designation'
    for d in dirs:
        row = t3.add_row().cells
        row[0].text = str(d.get("name"))
        row[1].text = str(d.get("designation"))
        
    # Section 8
    doc.add_heading("Section 8 — Data Quality Notes", 1)
    dnotes = analysis_result.get("data_quality_notes", [])
    for n in dnotes:
        doc.add_paragraph(str(n), style='List Bullet')
        
    # Footer
    for section in doc.sections:
        footer = section.footer
        p = footer.paragraphs[0]
        p.text = f"IntelliCredit | Confidential | {datetime.now().strftime('%Y-%m-%d')}"
        p.alignment = WD_ALIGN_PARAGRAPH.CENTER
        
    file_stream = io.BytesIO()
    doc.save(file_stream)
    file_stream.seek(0)
    return file_stream
